### ISSUE TITLE
Chrome crashing

### ISSUE THREAD

**Issue by aullman** [aullman/opentok-test-scripts#8]
Getting the following error:

https://travis-ci.org/aullman/opentok-textchat/builds/203309358
```
> protractor tests/protractor.conf.js
(node:1889) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[03:06:03] I/launcher - Running 1 instances of WebDriver
[03:06:03] I/direct - Using ChromeDriver directly...
[03:07:04] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64)
[03:07:04] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.8.12-040812-generic x86_64)
    at Object.checkLegacyResponse (/home/travis/build/aullman/opentok-textchat/demo/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/home/travis/build/aullman/opentok-textchat/demo/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/travis/build/aullman/opentok-textchat/demo/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/travis/build/aullman/opentok-textchat/demo/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/travis/build/aullman/opentok-textchat/demo/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/home/travis/build/aullman/opentok-textchat/demo/node_modules/protractor/built/driverProviders/direct.js:76:33)
    at Runner.createBrowser (/home/travis/build/aullman/opentok-textchat/demo/node_modules/protractor/built/runner.js:194:43)
    at q.then.then (/home/travis/build/aullman/opentok-textchat/demo/node_modules/protractor/built/runner.js:338:29)
    at _fulfilled (/home/travis/build/aullman/opentok-textchat/demo/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/travis/build/aullman/opentok-textchat/demo/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/travis/build/aullman/opentok-textchat/demo/node_modules/q/q.js:796:13)
    at /home/travis/build/aullman/opentok-textchat/demo/node_modules/q/q.js:556:49
    at runSingle (/home/travis/build/aullman/opentok-textchat/demo/node_modules/q/q.js:137:13)
[03:07:04] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.
```

**Comment by aullman** [comment]
Needed to make sure I set the display settings for Travis by adding this to the .travis.yml.

```
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
```
